<!--
SPDX-FileCopyrightText: 2025 Legiayayana

SPDX-License-Identifier: GPL-2.0-or-later
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>library</OutputType>
		<TargetFramework>$(DepotTargetFramework)</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>$(DepotArchiverVersion)</Version>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../DepotArchiver/DepotArchiver.csproj"/>
		<ProjectReference Include="../DepotACF/DepotACF.csproj" />
		<ProjectReference Include="../DepotUnarchiver/DepotUnarchiver.csproj"/>
		<ProjectReference Include="../DepotHealth/DepotHealth.csproj"/>
	</ItemGroup>

</Project>
