# SPDX-FileCopyrightText: 2025 Legiayayana
#
# SPDX-License-Identifier: GPL-2.0-or-later

name: Build
on: [ push ]
jobs:
    build:
        name: "Build [${{ matrix.rid }}]"
        strategy:
            matrix:
                rid: [ linux-x64, linux-musl-x64, linux-arm64, linux-musl-arm64, osx-arm64, osx-x64, win-x64 ]
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
                with:
                    fetch-depth: 0
                    submodules: 'recursive'
            -   uses: actions/setup-dotnet@v4
                with:
                    dotnet-version: 10.x
            -   run: dotnet publish PublishTarget -c Release -o ${{ github.workspace }}/Publish/DepotArchiver-Runtime/${{matrix.rid}} -f net10.0 -r ${{ matrix.rid }}
            -   run: dotnet publish PublishTarget -c Release -o ${{ github.workspace }}/Publish/DepotArchiver-Standalone/${{matrix.rid}} -f net10.0 -r ${{ matrix.rid }} --sc
            -   uses: actions/upload-artifact@v4
                with:
                    name: DepotArchiver-${{ matrix.rid }}
                    path: Publish/DepotArchiver-Runtime/${{matrix.rid}}
            -   uses: actions/upload-artifact@v4
                with:
                    name: DepotArchiver-${{ matrix.rid }}-Standalone
                    path: Publish/DepotArchiver-Standalone/${{matrix.rid}}
