<!--
SPDX-FileCopyrightText: 2025 Legiayayana

SPDX-License-Identifier: GPL-2.0-or-later
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFrameworks>$(DepotTargetFrameworks)</TargetFrameworks>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>$(DepotArchiverVersion)</Version>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="../DepotCommon/DepotCommon.csproj"/>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Spectre.Console" Version="0.54.1-alpha.0.79"/>
	</ItemGroup>

</Project>
